<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head> 
<link rel="stylesheet" type="text/css" href="<?= $this->urlHome ?>/css/forms.css" />
</head>
<body onload="document.login.username.focus();">
	<div id="top">
		<div id="header"><h1 class="blogtitle"><a href="<?= $this->urlHome ?>"><?= $this->pageTitle ?></a></h1></div>
	</div>
	<div id="nav" class="clearfix">
	 	<div id="nav2">
	 		<ul class="nav2"><li>Login with your network username and password</li></ul>
	 	</div>
	</div>
	<div id="main">
		<div id="error"><?= $this->message ?></div>
		<form action="<?= $this->urlHttps ?>/login/result" method="post" class="foobar_form" id="login" name="login">
			<input type="hidden" name="form_submitted" value="1">
			<div><label>User Name: </label><input type="text" name="username" id="username" /></div>
			<div><label>Password: </label><input type="password" name="password" id="password" /></div>
			<div><label>&nbsp;</label><input type="submit" name="submit" value="Submit" id="submit" /></div>
		</form>
	</div>
</body>
</html>

