<?= $this->partial('header.phtml', array(
    'from' => 'execute','urlHome' => $this->urlHome)); ?>


<?
/**************** test ground
<?php echo "this is it!" ?>
<br />
<?=  $this->id ?>
<br />
<?=  $this->release_vehicle_id ?>
<br />
<?= $this->release ?>
<br />
<?= $this->env ?>
<br />


<?php 
$comps = preg_split("/, /", $this->components);
foreach ( $comps as $comp) 
{
  echo $comp, "<br />";
}

?>
<br />

$comps = preg_replace(" ", "\n", $this->components_lines);
<?= $comps ?>
<br />


<?=  $this->username ?>
<br />
<?=  $this->components ?>
<br />
<?=  $this->plan ?>
<br />
<?=  $this->audit() ?>
<br />
<?=  $this->step ?>
<br />
<? echo "===" ?>
<?=  $this->sub_step ?>
<? echo "===" ?>
<br />

******************/
?>




<? 

echo "<h1>Steps to do audit:</h1>";

echo "<ul>";

echo "<li> login to rotozip<br />";
echo "<li> make sure you have ITOPS_HOME environment variable set</br />";
echo "<li> put the following in a file :</br /><br />";

echo "<br />";

$comps = preg_split("/, /", $this->components);
foreach ( $comps as $comp) 
{
  echo $comp, "<br />";
}


// prepare the string to use in cmd
$release_string_in_cmd = $this->release_vehicle_id . "-" .  $this->step ;
if (! empty($this->sub_step)) {
  $release_string_in_cmd .= "-" . $this->sub_step;
} 

echo "<br />";

//echo "components_for_file  " . "<br /><br />";
echo "<li> run:<br /> <br />";

echo " \$ITOPS_HOME/bin/massive_audit.pl -e " . $this->env . " -r " . $release_string_in_cmd .  " -f " . "{file} <br /><br />";


echo "<li>once the above run is done, it'll send out an email to siteops, with the following link to  the audit result page: <br /><br />";
//echo "http://rotozip.corp.foobar.com/cgi-bin/lwang/showAudit.pl?env=" . $this->env . "&release=" . $this->release . "RC" . $this->rcnumber  ;
//echo "<a href=\"" . "http://rotozip.corp.foobar.com/cgi-bin/lwang/showAudit.pl?env=" . $this->env . "&release=" . $this->release . "RC" . $this->rcnumber . "\"/>" . " here " . "</a>"; 

echo "<a href=\"" . "http://rotozip.corp.foobar.com/cgi-bin/lwang/showAudit.pl?env=" . $this->env . "&release=" . $release_string_in_cmd .  "\"/>" . " here " . "</a>"; 


echo "</ul>";

?>



<?= $this->partial('footer.phtml', array(
    'from' => 'execute','urlHome' => $this->urlHome)); ?>
