<?= $this->partial('header.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>

<form  method="post" action="<?= $this->urlHome ?>/index/copysave" id="create_form" enctype="multipart/form-data" class="foobar_form " style="padding:10px;">
	<input type="hidden" name="form_submitted" value="1" />
	<input type="hidden" name="release_vehicle_id" id="release_vehicle_id" />
	<input type="hidden" name="edit_from" value="<?= $this->releaseVehicle->release_vehicle_id ?>" />
	<fieldset id="create"><legend>Create Release Vehicle ID</legend>
	<div style="margin-top:10px;" ><label>Environment</label><?= $this->EnvList($this->releaseVehicle->env) ?></div>


        <div style="margin-top:10px;" ><label>Release Type</label><?= $this->TypeList() ?></div>

<!--
        <div><label>Release Vehicle ID:</label><span class="readonly">R</span><input type="text" id="id1" class="text required" /><span class="readonly" id="type_text">-TYPE</span><span class="readonly" id="env_text">-ENV-</span><span class="readonly">RC</span><input type="text" id="id2" class="text required" /><span id="id3" class="readonly">-<?= $this->count ?></span></div>
-->

	<div><label>Release Vehicle ID:</label><span class="readonly">R</span><input  type="text" id="id1" class="text required" /><span class="readonly" id="type_text">-TYPE</span><span class="readonly" id="env_text">-<?= $this->releaseVehicle->env ?>-</span><span class="readonly">RC</span><input type="text" id="id2" class="text required" /><span id="id3" class="readonly">-<?= $this->count ?></span></div>

<!--
	<div><label>Build Number:</label>
	<select name="build_no" class="required" id="build_no">
					<option value="<?= $this->releaseVehicle->build_no ?>"><?= $this->releaseVehicle->build_no ?></option>
<?php
					foreach ($this->builds as $build)  {
						echo "<option value='$build'>$build</option>";
					}
?>
				</select>
	</div>
-->

	<div style="margin-bottom:0px;"><label>DB Patches:</label><input type="text" name="db_patches" class="required" value="<?= $this->dbpatch ?> "/></div>
	<div class="grey"><label>&nbsp;</label>Comma Separated</div>
	<div><label>Components:</label>
		<select size="20" multiple="multiple" style="width:200px;" id="firstSelect">
			<option value="">&nbsp;</option>
		</select>
		<input type="button" style="width:auto;vertical-align:top;" id="movefront" value=">>" /> 
		<input type="button" style="width:auto;vertical-align:top;" id="moveback" value="<<" /> 
		
<?php
	$selected = $this->selectedComponents;
		$listhtml = '<select class="required" size="20" multiple="multiple" style="width:200px;" id="component_name" name="component_name[]">';
		foreach ($selected as $comp)  {
			$listhtml .= "<option value='" . $comp->component_name . "'>" . $comp->component_name .  "</option>";
		}
		$listhtml.= "</select>";

?>
	<?= $listhtml ?>    
	</div>
	
	<div><label>&nbsp;</label><input type="submit" value="submit"  name="submit" id="submit" /></div>
	</fieldset>
</form>

<script>

function show3(){
                var str = $('#id1').val();
                $.ajax({
                  url: url_home + "/index/ajax3?this_release="+encodeURIComponent(str),
                  cache: false,
                  success: function(html){
                        $("#firstSelect").empty().append(html);
                  }
                });
}

$(document).ready(function() {
// GLU: show release->components, by using LEGACY-MASTER.BOM
        show3();
        $('#id1').bind("change",show3);
});

/********* pre GLU way
function show(){
		var str = $('#build_no').val();
		$.ajax({
		  url: url_home + "/index/ajax?build="+encodeURIComponent(str),
		  cache: false,
		  success: function(html){
		  	 $("#firstSelect").empty().append(html);
		  }
	 	});
}
$(document).ready(function() {
	show();
	$('#build_no').bind("change",show);	
});
**********/

</script>
<?= $this->partial('footer.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>
