<?= $this->partial('header.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>

<form  method="post" id="create_form" action="<?= $this->urlHome ?>/index/editsave?id=<?= $this->releaseVehicle->release_vehicle_id ?>"  enctype="multipart/form-data" class="foobar_form " style="padding:10px;">
	<input type="hidden" name="form_submitted" value="1" />
	<input type="hidden" name="release_vehicle_id" value="<?= $this->releaseVehicle->release_vehicle_id ?>" />
	<input type="hidden" name="env" value="<?= $this->releaseVehicle->env ?>" />
        <input type="hidden" name="this_release" id="this_release" value="<?= $this->release ?>" />
	<fieldset id="create"><legend>Edit Release Vehicle ID</legend>
	<div style="margin-top:10px;" ><label>Environment</label><span class="readonly"><?= $this->releaseVehicle->env ?></span></div>
	<div><label>Release Vehicle ID:</label><span class="readonly"><?= $this->releaseVehicle->release_vehicle_id ?></span></div>
	<div><label>Build Number:</label>
	<select name="build_no" class="required" id="build_no">
			<option value="<?= $this->releaseVehicle->build_no ?>"><?= $this->releaseVehicle->build_no ?></option>
<?php
		foreach ($this->builds as $build)  {
			echo "<option value='$build'>$build</option>";
		}
?>
	</select>
	</div>
	
	<div style="margin-bottom:0px;"><label>DB Patches:</label><input type="text" name="db_patches" class="required" value="<?= $this->dbpatch ?> "/></div>
	<div class="grey"><label>&nbsp;</label>Comma Separated</div>
	<div><label>Components:</label>
		<select size="20" multiple="multiple" style="width:200px;" id="firstSelect">
			<option value="">&nbsp;</option>
		</select>
		<input type="button" style="width:auto;vertical-align:top;" id="movefront" value=">>" /> 
		<input type="button" style="width:auto;vertical-align:top;" id="moveback" value="<<" /> 
		
<?php
		$selected = $this->selectedComponents;
//		print_r($selected);
// Zend_Db_Table_Rowset Object ( [_data:protected] => Array ( 
// [0] => Array ( [id] => 8576 [release_vehicle_id] => R111-stg-RC-1-106 [component_id] => 0 [component_name] => abook ) 
// [1] => Array ( [id] => 8577 [release_vehicle_id] => R111-stg-RC-1-106 [component_id] => 0 [component_name] => abook-cloud )
// ...
// 
		$sorted_selected = array();
		foreach ( $selected as $comp)  {
			array_push( $sorted_selected, $comp->component_name );
		}
		asort( $sorted_selected );

		$listhtml = '<select size="20" class="required" multiple="multiple" style="width:200px;" id="component_name" name="component_name[]">';
		foreach ($sorted_selected as $c)  {
			$listhtml .= "<option value='" . $c . "'>" . $c .  "</option>";
		}
/*
		foreach ($selected as $comp)  {
			$listhtml .= "<option value='" . $comp->component_name . "'>" . $comp->component_name .  "</option>";
		}
*/
		$listhtml.= "</select>";

?>
	<?= $listhtml ?>    
	</div>
	
	<div><label>&nbsp;</label><input type="submit" value="submit"  name="submit" id="submit" /></div>
	</fieldset>
</form>

<script>
function show(){
                var str1 = $('#this_release').val();
		var str = $('#build_no').val();
		$.ajax({
//                url: url_home + "/index/ajax?build="+encodeURIComponent(str),
                  url: url_home + "/index/ajax?this_release="+encodeURIComponent(str1)+"&build="+encodeURIComponent(str),
		  cache: false,
		  success: function(html){
		  	 $("#firstSelect").empty().append(html);
		  }
	 	});
}
$(document).ready(function() {
	show();
	$('#build_no').bind("change",show);	
});
</script>
<?= $this->partial('footer.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>
