<?= $this->partial('header.phtml', array(
    'from' => 'execute','urlHome' => $this->urlHome)); ?>
<script type="text/javascript">
/*$(document).ready(function() {
	$(".other").submit(function(event){
		event.preventDefault(); 
		var str = $(this).serialize();
		$.ajax({
			type: "POST",
			url: url_home + "/index/other",
			data: str
		});
		$(this).find("input.submit").blur();
		$(this).find("input.submit").attr("disabled","true").attr("value", "Completed");
		$(this).parent().parent().next().find("input.submit").attr("disabled","");
	});

	$(".bypass").submit(function(event){
		event.preventDefault(); 
		var str = $(this).serialize();
		$.ajax({
			type: "POST",
			url: url_home + "/index/other",
			data: str
		});
		$(this).prev().find("input.submit").attr("disabled","true").attr("value", "Completed");
		$(this).remove();
		
	});
}); */

/******** lwang: needs fine-tuning
     $(document).ready(function(){

     $("#button_start").click(function(event){
        $("#status_area").text("In Progress");
        $("#button_start").attr('disabled', 'true');
        return false;
     });


     $("#button_complete").click(function(event){
        $("#status_area").text("Completed");
        $("#button_start").attr('disabled', 'true');
        $("#button_complete").attr('disabled', 'true');
        $("#button_bypass").attr('disabled', 'true');
        return false;
     });


     $("#button_bypass").click(function(event){
        $("#status_area").text("Bypassed");
        $("#button_start").attr('disabled', 'true');
        $("#button_complete").attr('disabled', 'true');
        $("#button_bypass").attr('disabled', 'true');
        return false;
     });



   });

************/


</script>

<!--
<a href="<?php $p1 = $this->release_vehicle_id; $p2 =  str_replace("execute", "editrollout", $p1);  echo $p2; ?> " >  Edit Rollout </a>
-->

<!--
<a href="<?php
                $redirectUrl =  Zend_Registry::get('foobarconfig')->url->web . "/index/editrollout?id=" . $this->release_vehicle_id . "&edit_from=" . $release_vehicle_id ;
//echo $redirectUrl;
echo $this->release_vehicle_id;
    //            $this->_redirect($redirectUrl);
?>" > Edit </a>
-->

	<?= $this->executeList() ?>
<!--
	<meta http-equiv=refresh content="5; url=<?php echo $_SERVER['PHP_SELF']; ?>">
-->

<?= $this->partial('footer.phtml', array(
    'from' => 'execute','urlHome' => $this->urlHome)); ?>
