<?= $this->partial('header.phtml', array(
    'from' => 'manifest', 'urlHome' => $this->urlHome)); ?>

<!--
<h1> Manifests: </h1>
-->

Manifests ( using GLU API ):

<ul>
<li> <a href="http://tools01.corp.foobar.com:8888/?env=ei1" target="_blank" > Manifest for EI1  </a> </li>
<br />
<li> <a href="http://tools01.corp.foobar.com:8888/?env=ei3" target="_blank" > Manifest for EI3  </a> </li>
<br />
<li> <a href="http://tools01.corp.foobar.com:8888/?env=stg" target="_blank" > Manifest for STG-ALPHA  </a> </li>
<br />
<li> <a href="http://tools01.corp.foobar.com:8888/?env=beta" target="_blank" > Manifest for STG-BETA  </a> </li>
<br />
<li> <a href="http://tools01.corp.foobar.com:8888/?env=ech3" target="_blank" > Manifest for ECH3  </a> </li>
<br />
<li> <a href="http://tools01.corp.foobar.com:8888/?env=ela4" target="_blank" > Manifest for ELA4  </a> </li>
<br />

</ul>



Manifests (cgi scripts to query relrepo): (  <a href="https://sandbox01.corp.foobar.com/lwang/glu/manif/README" target="_blank" > how to update? </a>  )

<ul>
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=ei1" target="_blank" > Manifest for EI1  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=ei3" target="_blank" > Manifest for EI3  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=stg" target="_blank" > Manifest for STG  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=beta" target="_blank" > Manifest for BETA  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=ech3" target="_blank" > Manifest for ECH3  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/rb/genManifest.cgi?env=ela4" target="_blank" > Manifest for ELA4  </a> </li>
<br />

</ul>


Manifests (legacy):  ( <a href="https://sandbox01.corp.foobar.com/lwang/legacy/manif/README" target="_blank" > how to update? </a>  )

<ul>
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/showManifest.pl?env=stg&action=legacy" target="_blank" > Manifest for STG  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/showManifest.pl?env=beta&action=legacy" target="_blank" > Manifest for BETA  </a> </li>
<br />
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/showManifest.pl?env=ech3&action=legacy" target="_blank" > Manifest for ECH3  </a> </li>
<br />
</ul>

Netstat analyzer:

<ul>
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/netstat/analyzer.pl" target="_blank"> netstat analyzer </a>  ( see <a href= 'http://rotozip.corp.foobar.com/cm/netstat/REAME'> here </a>  for the meaning of columns )
<br />
</ul>

<br />
Disk usage analyzer:

<ul>
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/disk_usage_mon/analyzer.pl" target="_blank"> disk usage analyzer for Tony </a>
<br />
</ul>

<!--
<br />
Fabrics Audit:

<ul>
<li> <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/py/show_audit_fabrics.py" target="_blank"> show fabrics audit </a>
<br />
</ul>
-->


<?= $this->partial('footer.phtml', array(
    'from' => 'search','urlHome' => $this->urlHome)); ?>
