<?= $this->partial('header.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>


<form  method="post" action="<?= $this->urlHome ?>/index/create"  id="create_form" enctype="multipart/form-data" class="foobar_form " style="padding:10px;">
	<input type="hidden" name="form_submitted" value="1" />
	<fieldset id="create"><legend>Create Release Vehicle ID</legend>
	<div style="margin-top:10px;" ><label>Environment</label><?= $this->EnvList() ?></div>
	<div style="margin-top:10px;" ><label>Release Type</label><?= $this->TypeList() ?></div>
	<div><label>Release Vehicle ID:</label><span class="readonly">R</span><input type="text" id="id1" class="text required" /><span class="readonly" id="type_text">-TYPE</span><span class="readonly" id="env_text">-ENV-</span><span class="readonly">RC</span><input type="text" id="id2" class="text required" /><span id="id3" class="readonly">-<?= $this->count ?></span></div>
	<input type="hidden" name="release_vehicle_id" id="release_vehicle_id" />
<!--

	<div><label>Build Number:</label>
				<select name="build_no" class="required" id="build_no">
					<option value="">Select Build Number</option>
<?php
					foreach ($this->builds as $build)  {
						echo "<option value='$build'>$build</option>";
					}
?>
				</select>
	</div>
-->

	<div><label>Using Bom:</label>
	<select>
<!--
		<option value="LEGACY-MASTER.BOM"> LEGACY-MASTER.BOM </option>
-->
		<option value="RELEASE.BOM"> RELEASE.BOM </option>
	</select>
	</div>

	<div style="margin-bottom:0px;"><label>DB Patches:</label><input type="text" name="db_patches" class="required" /></div>
	<div class="grey"><label>&nbsp;</label>Comma Separated</div>
	<div><label>Components:</label>
		<select size="20" multiple="multiple" style="width:200px;" id="firstSelect">
			<option value="">&nbsp;</option>
		</select>
		<input type="button" style="width:auto;vertical-align:top;" id="movefront" value=">>" /> 
		<input type="button" style="width:auto;vertical-align:top;" id="moveback" value="<<" /> 

		<select size="20" class="required" style="width:200px;" multiple="multiple" id="component_name" name="component_name[]"> 
		</select>     

<!--
	<input type="button" value="read from file" style="width:auto;align:top;"  />
-->

	</div>
	

	<div><label>&nbsp;</label><input type="submit" value="submit"  name="submit" id="submit" />  ( <font color='red'> Make sure components on the right are selected before submitting! </font> ) </div>  
	
	</fieldset>
</form>


<script>
function show2() {
                var str = $('#id1').val();
                $.ajax({
                  url: url_home + "/index/ajax2?this_release="+encodeURIComponent(str),
                  cache: false,
                  success: function(html){
                         $("#build_no").empty().append(html);
                  }
                });

}
function show(){
                var str1 = $('#id1').val();
		var str = $('#build_no').val();
		$.ajax({
                  url: url_home + "/index/ajax?this_release="+encodeURIComponent(str1)+"&build="+encodeURIComponent(str),
		  cache: false,
		  success: function(html){
		  	 $("#firstSelect").empty().append(html);
		  }
	 	});
}
function show3(){
		var str = $('#id1').val();
		$.ajax({
		  url: url_home + "/index/ajax3?this_release="+encodeURIComponent(str),
		  cache: false,
		  success: function(html){
			$("#firstSelect").empty().append(html);
		  }
		});
}

$(document).ready(function() {
// GLU: show release->components, by using LEGACY-MASTER.BOM
	show3();
	$('#id1').bind("change",show3);

// GLU: show release->build->components
/*
        show2();
        $('#id1').bind("change",show2);

	show();
	$('#build_no').bind("change",show);	
*/
});
</script>
<?= $this->partial('footer.phtml', array(
    'from' => 'rollout','urlHome' => $this->urlHome)); ?>
