<?= $this->partial('header.phtml', array(
    'from' => 'newworkflow','urlHome' => $this->urlHome)); ?>


<!--
  <form method="post" action="http://sandbox01.corp.foobar.com/cgi-bin/lwang/tulip/workflow/create.pl" id="create_form_workflow" class="foobar_form " style="padding:10px;" >
-->
  <form method="post" action="<?php echo $this->urlHome ?>/index/createworkflow" id="create_form_workflow" class="foobar_form " style="padding:10px;" >
  <input type="hidden" name="form_workflow_submitted" value="1" />

  <p />
	<fieldset id="create"><legend>Create Release Workflow ID</legend>
  <div class="row requiredRow">
        <label for="txt_Release" id="Release-ariaLabel">Release: </label>

        <input id="txt_Release" name="txt_Release" type="text" aria-labelledby="Release-ariaLabel" class="required" title="Release. This is a required field" />
        (no space in release name, e.g., R1010-RC2)
  </div>
  <p />
  <div class="row requiredRow">
        <label for="sel_Step" id="Step-ariaLabel">Step: </label>
        <select id="sel_Step" name="sel_Step" aria-labelledby="Step-ariaLabel" class="required" title="Step. This is a required field">
 
<option value="Step_1"> Step 1: checkins completed for all approved fixes and branch locked (release owner) </option>
<option value="Step_2"> Step 2: enumerate all required components to be built (release owner) </option>
<option value="Step_3"> Step 3: build required components (build master) </option>
<option value="Step_4"> Step 4: push build to STG-BETA (Ops) </option>
<option value="Step_5"> Step 5: test the build (QA) </option>
<option value="Step_6"> Step 6: production deployment (Ops) </option>
<option value="Step_7"> Step 7: sanity test in production (QA) </option>

        </select>

  </div>
  <p />

  <div class="row">
        <label for="txt_Status" id="Status-ariaLabel">Status:  </label>
        <input id="txt_Status" name="txt_Status" type="text" aria-labelledby="Status-ariaLabel" class="required" title="Status. This is a required field" value="Done" />
  </div>
  <p />

  <div class="row">
        <label for="txtarea_Notes" id="Notes-ariaLabel">Notes: </label>
        <textarea id="txtarea_Notes" name="txtarea_Notes" cols="20" rows="3" aria-labelledby="Notes-ariaLabel" title="Step. This is a required field"></textarea>
  </div>
  <p />
  <div class="row">

  <div><label>&nbsp;</label><input type="submit" value="Done"  name="submit" id="submit" /> 
  </div>
  </fieldset>
  </form>



<?= $this->partial('footer.phtml', array(
    'from' => 'footer','urlHome' => $this->urlHome)); ?>
