<?= $this->partial('header.phtml', array(
    'from' => 'other','urlHome' => $this->urlHome)); ?>

<?php if ($this->task == "audit") {  ?>    
	<h1>Steps to do audit:</h1>
	<style>
	   ul.steps li {padding:5px;} 
	    
	</style>
	<ul class="steps">
	<li>login to rotozip</li>
	<li>make sure you have ITOPS_HOME environment variable set</li>
	<li>put the following in a file :
	<?php foreach ($this->components as $component) {  ?>
	<?= $component ?> <br/>
	<?php } ?>
	
	</li>
	<li>run:<br/>
	
	      $ITOPS_HOME/bin/massive_audit.pl -e <?= $this->env ?> -r <?= $this->release_vehicle_id ?> -f {file}
	</li>
	<li>once the above run is done, it'll send out an email to siteops, with the following link to the audit result page:<br/>
	
	      <a href="http://rotozip.corp.foobar.com/cgi-bin/lwang/showAudit.pl?env=<?= $this->env ?>&release=<?= $this->release_vehicle_id ?>">here </a>
	</li>
	</ul>
<?php }else {?>
<h1> You have to manually execute this step for the time being. Please don't forget to go back <a href="<?= $this->urlHome ?>/index/execute?id=<?= $this->release_vehicle_id ?>">here</a> and click on complete once this step has been completed.</h1>

<?php } ?>
<?= $this->partial('footer.phtml', array(
    'from' => 'other','urlHome' => $this->urlHome)); ?>
    
    
