<?= $this->partial('header.phtml', array(
    'from' => 'ssh','urlHome' => $this->urlHome)); ?>

<form action="<?= $this->urlHttps ?>/outsideurl" method="post" class="foobar_form" id="login" name="login">
	<input type="hidden" name="form_submitted" value="1">
	<input type="hidden" name="machine" value="<?= $this->machine ?>">
	<input type="hidden" name="task" value="<?= $this->task ?>">
	<div><label>Machine Name: </label><span class="readonly"><?= $this->machine ?></span></div>
	<div><label>Task: </label><span class="readonly"><?= $this->task ?></span></div>
	<div><label>User Name: </label><input type="text" name="user_name"  value="" /></div>
	<div><label>Password: </label><input type="password" name="pass_word" value="" /></div>
	<div><label>&nbsp;</label><input type="submit" name="submit" value="Submit" id="submit" /></div>
	</form>
<?= $this->partial('footer.phtml', array(
    'from' => 'ssh','urlHome' => $this->urlHome)); ?>