<?= $this->partial('header.phtml', array(
    'from' => 'workflow','urlHome' => $this->urlHome)); ?>

(under construction...)

<div class="clearfix" style="padding:5px;width:100%;">
<?php if ($this->value == 1){ ?>
        <div style="float: left;">
                <a href="<?= $this->urlHome ?>/index/newworkflow" >[Create New Workflow]</a>
        </div>


	<div style="float: right;">
		<a href="https://sandbox01.corp.foobar.com/cgi-bin/lwang/tulip/workflow/show.pl" target="_blank"> show </a>
	</div>

<?php } ?>

<!--
        <div id="pager"  style="float:right;">
                <form class="search" >
                        <img src="<?= $this->urlHome ?>/images/icons/first.png" class="first"/>
                        <img src="<?= $this->urlHome ?>/images/icons/prev.png" class="prev"/>
                        <input type="text" class="pagedisplay"/>
                        <img src="<?= $this->urlHome ?>/images/icons/next.png" class="next"/>
                        <img src="<?= $this->urlHome ?>/images/icons/last.png" class="last"/>
                        <select class="pagesize" id="pagesize">
                                <option selected="selected"  value="10">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option  value="40">40</option>
                        </select>
                </form>
        </div>
-->


</div>


        <?= $this->workflowList() ?>

<p /><p /><p /><p />
<hr>
<p /><p /><p /><p />
<h2> NOTES: </h2>
<ul>
<li>  Step_1: checkins completed for all approved fixes and branch locked (release owner) </option>
<li>  Step_2: enumerate all required components to be built (release owner) </option>
<li>  Step_3: build required components (build master) </option>
<li>  Step_4: push build to STG-BETA (Ops) </option>
<li>  Step_5: test the build (QA) </option>
<li>  Step_6: production deployment (Ops) </option>
<li>  Step_7: sanity test in production (QA) </option>
</ul>


<?= $this->partial('footer.phtml', array(
    'from' => 'workflow','urlHome' => $this->urlHome)); ?>
