signal:
  repo : http://svn.corp.foobar.com:8070/svn/netrepo/signal/trunk/release
  rel : SIG002
 
userhistory:
  repo : http://svn.corp.foobar.com:8070/svn/litemp/userhistory/trunk/release
  rel : UH005
 

nus:
  repo : http://svn.corp.foobar.com:8070/svn/netrepo/nus/trunk/release
  rel : NUS-0.1111.1
