#!/bin/bash

env=${1:?"Give me an env, e.g., ech3, beta, stg"}

echo Checking JDK6 in $env ....

apps=` ../../bin/cmtool.pl -a get_pools -env $env`

echo $apps

for i in $apps; do 
#  echo ===== $i
  ./audit_jdk.rb -e $env -a $i -s
done

