#!/bin/bash

env=${1:?"Give me an env, e.g., ech3, beta, stg"}

echo Checking front end apps in  $env ....

fe_apps=`cat ../../manif/container_mapping_$env | cut -f1`

echo $fe_apps


for i in $fe_apps; do 
  if [ -n "`./audit_tomcat.rb -e $env -a $i | grep LIN0`" ]; then
    echo $i
  fi
done

