#!/bin/bash
#
# lwang: This is the entrance script to run 
#
#
if [[ "`hostname`" != 'rotozip.corp' ]]; then
  echo "run it on rotozip."
  exit
fi

if [ ! $# -eq 2 ]; then
  cat <<USAGE

  $0 <env>  <number of runs>

e.g.,

  $0 beta  5
        - this will collect disk usage for beta 5 times, once per hour 

	- if you want to run once for an env, just run ./get_disk_usage.sh

	- view the results at:  http://rotozip.corp.foobar.com/cgi-bin/lwang/disk_usage_mon/analyzer.pl  

USAGE
  exit
fi

# now that we have the right number of args
env=$1
number_of_runs=$2
#echo $env

loop=$number_of_runs   #  adjust together with sleep 

#echo $loop

while  true; do
  ./get_disk_usage.sh $env
  loop=`expr $loop - 1`
  if [[ $loop -lt 1 ]]
  then
    break 
  fi
  sleep 3360   #  3600  ( 1 hour) taken away 240 ( 4 minutes ) . Reason: Tony wants it to run once per hour, but each run takes about 4 minutes
done 

function trap_exit
{
  echo
  echo "view your results at: http://rotozip.corp.foobar.com/cgi-bin/lwang/disk_usage_mon/analyzer.pl?env=$env"
  echo
}
trap 'trap_exit; exit 2' 0 1 2 3 9 15 24


